### ISSUE TITLE
Doesn't compile on ubuntu 14.04, 64bit

### ISSUE THREAD

**Issue by giantpune** [json-c/json-c#169]
```
json_tokener.c: In function 'json_tokener_parse_ex':
json_tokener.c:355:6: error: variable 'size' set but not used [-Werror=unused-but-set-variable]
  int size;
      ^
cc1: all warnings being treated as errors
make[2]: *** [json_tokener.lo] Error 1
```

**Comment by rgerhards** [comment]
This is probably a duplicate of https://github.com/json-c/json-c/issues/159
