### ISSUE TITLE
Mac: uselocale failed to build

### ISSUE THREAD

**Issue by alexukr** [json-c/json-c#246]
It seems like recent changes (uselocale) broke the build on Mac (I use OS X El Capitan 10.11.6).
I run:
git clone https://github.com/json-c/json-c
cd json-c
./autogen.sh
./configure
make

And it fails with:
Making all in .
  CC       arraylist.lo
  CC       debug.lo
  CC       json_c_version.lo
  CC       json_object.lo
  CC       json_object_iterator.lo
  CC       json_tokener.lo
json_tokener.c:239:3: error: use of undeclared identifier 'locale_t'
  locale_t oldlocale = uselocale(NULL);

**Comment by hawicz** [comment]
Does your environment not have locale.h?  What does the uselocale man page say about what needs to be included to use it?

**Comment by hawicz** [comment]
Never mind, it needs xlocale.h.  It seems that OSX and others use that, and Linux is the odd one out with just locale.h.  s/b easy to fix

**Comment by alexukr** [comment]
Now it works again. Thanks.
