### ISSUE TITLE
Undefined symbols Error for architecture x86_64 on Mac 

### ISSUE THREAD

**Issue by imkimchi** [json-c/json-c#235]
Xcode prints out the error as the title when i try to compile source.

    Undefined symbols for architecture x86_64:
     "_json_object_to_json_string_ext", referenced from:
       _main in main.o
     "_json_tokener_parse", referenced from:
      _main in main.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Definitely all libraries in /usr/local/lib and include in /usr/local/include.
I am working on Mac OS X 11.4 and using 0.12 version of json-c

Additionally, gcc couldn't find json.h header file when i don't include header file as direct path like(/usr/local/Cellar/json-c/0.12/include/json-c/json.h). 

<b>problem solved</b>
It works fine if you give -I/usr/local/include -L/usr/local/lib option and -ljson-c option
> gcc -I/usr/local/include -L/usr/local/lib test.c -o test -ljson-c

**Comment by hawicz** [comment]
Unless you already have a copy of json-c installed in /usr/local, that doesn't make any sense.  Until you run "make install", the build should occur locally (and once you do libtool should re-link things so they'll work in the install location).

I've never tried building json-c on a Mac, and I don't have one on which I could, but perhaps if you show what the actual failing command is we might be able to figure out what's going wrong.

**Comment by hawicz** [comment]
Glad to hear you solved your problem.
